import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { HmacSha256 } from "https://deno.land/std@0.160.0/hash/sha256.ts";

const IOT_SECRET = Deno.env.get("IOT_HMAC_SECRET") || "leadfarm_iot_secret_2026";

serve(async (req) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    const payload = await req.json();
    const { sensor_id, timestamp, data, hmac } = payload;

    // 1. HMAC Verification
    // The signature should be generated by ESP32 using: 
    // HMAC_SHA256(SECRET, SENSOR_ID + TIMESTAMP + DATA_JSON)
    const dataString = JSON.stringify(data);
    const message = `${sensor_id}${timestamp}${dataString}`;
    
    const hasher = new HmacSha256(IOT_SECRET);
    hasher.update(message);
    const expectedHmac = hasher.toString();

    if (hmac !== expectedHmac) {
      console.error(`Invalid HMAC for sensor ${sensor_id}. Expected: ${expectedHmac}, Got: ${hmac}`);
      return new Response(JSON.stringify({ error: "Unauthorized: Invalid Signature" }), { 
        status: 401, 
        headers: { "Content-Type": "application/json" } 
      });
    }

    // 2. Database Insertion
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    // Prepare measurements
    // We map the payload keys to identifiant_type_mesure (this should be dynamic in production)
    const typeMapping: Record<string, number> = {
      "temp": 1, // Air Temperature
      "hum": 2,  // Air Humidity
      "soil": 3, // Soil Moisture
      "batt": 4  // Battery Level
    };

    const measurements = Object.entries(data).map(([key, value]) => ({
      identifiant_capteur: sensor_id,
      identifiant_type_mesure: typeMapping[key] || 99, // Fallback to 'Other'
      horodatage: new Date(timestamp).toISOString(),
      valeur_mesuree: value,
      unite_mesure: key === "temp" ? "°C" : "%"
    }));

    const { error } = await supabaseAdmin
      .from("MESURE_IOT")
      .insert(measurements);

    if (error) throw error;

    return new Response(JSON.stringify({ status: "success", received: measurements.length }), {
      headers: { "Content-Type": "application/json" }
    });

  } catch (err) {
    console.error("IoT Ingestion Error:", err);
    return new Response(JSON.stringify({ error: err.message }), { 
      status: 500, 
      headers: { "Content-Type": "application/json" } 
    });
  }
});
