-- Seed référentiel Groupe Lechehab (généré depuis docs/lechehab-referentiel.json)
-- Matières actives
insert into lf_active_ingredients (name) values ('75 g/L méfentrifluconazole') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Abamectine 18 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Acequinocyl') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Acétamepride SL 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Acrinathrine 75 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Alpha-Cyperméthrine 100 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Bifénazate 240 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Bifenthrine') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Boscalid 200 g/l, Krésoxim-Methyl 100 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Boscalid 252 g/kg, Pyraclostrobine 128 g/kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Captan 50% WP') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Captan 80% WG') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Chlorpyriphos 2%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Chlorpyriphos 480g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('CLOFENTEZINE+ BIFENTHRINE') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cuivre 4,5%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cyantraniliprole') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cycloxydine') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cymoxanil 2,85% w/w + Fosetyl Aluminum 30% w/w + Cuivre 16% w/w') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cyprodinil 37,5 %, Fludioxonil 25 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Cyprodinil 50%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Deltamethrine 25g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Difenoconazole 125 g/l, Azoxystrobine 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Difénoconazole 250 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Difenoconazole, Azoxystrobine') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dimethomorphe 150 g/kg, Dithianon 350 g/kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dimethomorphe 60 g/kg, cuivre 400 g/kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dimethomorphe 72 g/l, Pyraclotrobine 40 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dimétoate') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dithianon 500 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dithianon 70%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Dodine 400 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Emamectin Benzoate 50 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Etofenprox 287,5 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fenhexamid 500 g/kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fenoxycarbe 25 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fenpyroximate 5%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('FLUAZIFOP-P-BUTYL') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fluazinam 500g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Flupyradifurone 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fo Métalaxyl-M 5%, Folpel 40 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fosetyl Aluminium 500 g/kg, Folpel 250 g/kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fosetyl Aluminium 666,7g/Kg, Fluopicolide 444g/Kg') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Fosétyl-Aluminium 80 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Glufosinate Ammonium 15 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Glyphosate') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Hexythiazox') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Huile Blanche') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Huile de paraffine 830 g/L') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Huile Minérale 76 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Hydroxyde de cuivre 400 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Imidaclopride') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Imidaclopride OD 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Indaziflam 500 g/L') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Keroxim Methyl 50%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Lambda cyhalothrine') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Lufenuron 50 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Metrafenone 500 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Myclobutanil 240 g/L') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Oxychlorure de Cuivre 678,6 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Oxyfluorfen 240 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Penconazole 100 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Phosmet 50%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Propineb 70%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Proquinazid 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Pyridabene 20 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('PYRIFLUQUINAZON 20 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Pyriproxifène 100 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Soufre Miconisé Atomisé') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spinetoram 120 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spinosad') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spirodiclofen 240 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spiromesifen 240 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spirotetramat') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Spiroxamine 300 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Sulfate de cuivre 80%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Tebuconazole 200 g/l, Fluopyram 200 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Tebuconazole 250 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Tebufenpyrad') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Teflubenzuron 150g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Tetraconazole 40 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiaclopride 280 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiafloxystrobine 50%') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiamethoxam 200 g/l , chlorantraniliprole 100 g/l') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiamethoxam SC 25 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiamethoxam WG 25 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiophanate methyl') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Thiram 80 %') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Tolfenpyrad') on conflict (name) do nothing;
insert into lf_active_ingredients (name) values ('Triadimenol 250 g/L') on conflict (name) do nothing;

-- Fournisseurs
insert into lf_suppliers (name, role) values ('ACI', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('AGRICHEM', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('AGRO HERO', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('AGROTECH', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('AGROTODAY', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('ANGLO GULF', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('ASMIDAF', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('BAYER', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('BIGAGRI', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('BLIDA', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('CASAP', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('DAHRA CHEMICALS', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('DEVAGRI', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('DOUDAH', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('FILAHIA', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('FITOPHARM', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('FMC', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('HYGINDUST', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('MAHALIA', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('MAHALIA TAYEB', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('MAHALIYA TAYEB', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('MOSTA BOUSTANE', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('PROFERT', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('SIPCAM', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('SOMEDIA', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('SRID', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('TAYEB MAHALIA', 'distributor') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('VAPCO', 'manufacturer') on conflict (name) do nothing;
insert into lf_suppliers (name, role) values ('ZEGLA', 'distributor') on conflict (name) do nothing;

-- Produits
insert into lf_products (name, category, unit) values ('AMISTAR', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('AZOFOL', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('BLACK JAK', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Citric Acide', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('CORSAL', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('CROX FER EDDHA', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('CROX FOLIAIR', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('CROX MICRO MULTI', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('DIAFERRANE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FERIK', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FERTIGEL 00.52.34', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FLOWERING', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FLOXIDAN', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FUSILAD MAX', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('GOLD FOS', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('GREEN ZINC', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('KAOFOURMI', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('KARATE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('METHOATE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('MICROTHEOL SOUFRE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('NITRATE DE MAGNESIUM', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('REGALIS', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('STILO', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('VALLETTE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('VAPCOMOR', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('VITENE TRIPLO', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('WUXAL CUIVRE', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Abyss', 'AUTRE', 'l', 'ALGUES', 'Mannto 1%, AA 0.3%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('AgriM', 'AUTRE', 'l', 'MO', 'Matière Organique 40 % , Extrait humique 35 % ,Potassium organique 2,5 % , Azote organique 1 % ,Phosphore organique 0,1 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('ANTISAL', 'AUTRE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Arbofix', 'AUTRE', 'kg', 'Acide Alpha Naphtil acetique 1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Atlantica Nutricat ZN MN', 'AUTRE', 'kg', 'ZN + MN', 'Mn 17% + Zn 28%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Attrac', 'AUTRE', 'l', 'N', 'Azote 5%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Auxym', 'AUTRE', 'l', 'B 0.4%+Fer 0.6%+Mn 0.6%+ Cu 0.2%+ Zn 0.4%+ Mo 13%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Azofol SR', 'AUTRE', 'l', 'Azote 355 G/L + OE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Baypotass', 'AUTRE', 'l', 'Potassium 39%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('BB5', 'AUTRE', 'l', 'ACIDIFIANT', 'N 3% + P2O5 18,1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('BIO GRAND', 'AUTRE', 'kg', 'Glycine 40%+ Acide gibberellique 0,7%+ ANA 25%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('BIOCLEAR', 'AUTRE', 'l', 'SAVON', 'Savon potassique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Blackjak', 'AUTRE', 'l', 'ACIDE HUMIQUE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Boraminal', 'AUTRE', 'l', 'B', 'Azote total 4,1 % , Bore 4,6 % , Acides aminés 7,2% ,Matiere Organique 27 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('BoroZinc', 'AUTRE', 'kg', 'B + ZN', 'Bore Zinc') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Brevis', 'AUTRE', 'kg', 'Metamitron puro150 g/kg coformulanti q.b.a') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('C0RSAL', 'AUTRE', 'l', 'Oxyde ca 9%+ Oxyde Mg 1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Calboron', 'AUTRE', 'kg', 'CA', 'oxyde de Ca 30%+ bore 1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CAPFOL', 'AUTRE', 'l', 'Chlorure de Ca+Zn') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CarboFer', 'AUTRE', 'kg', 'P 8%, K 10%, Fer 1.8%, Carbohydrate 40%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Citoquin Mix', 'AUTRE', 'l', 'N 4%, P 8%, K 10,4%, B 0,42%, Mo 0,2%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CLEAR', 'AUTRE', 'l', 'Acides aminés + micronutriments chélatés') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Clerthin', 'AUTRE', 'kg', 'ana -amida 8.4,%p/p (84g/kg)') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Corex Zn Mn', 'AUTRE', 'l', 'Zn Mn') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CROX FOLIAIRE', 'AUTRE', 'l', 'Engrais foliaire NPK + oligo-éléments') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CROX MICRO', 'AUTRE', 'kg', 'Fer eddha 4,8%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory) values ('CROX MULTI', 'AUTRE', 'kg', 'NOUVAU') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CroxX kelp', 'AUTRE', 'l', 'Les algues 30%, oxyde de potassium 3,4 %, Oxyde de soufre 2,4 %, Glucides 1%, Carbone organique 0,6%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('CURANE', 'AUTRE', 'kg', 'P 58%, K 38%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Decco shield', 'AUTRE', 'l', 'Ca') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Delphos Ca', 'AUTRE', 'l', 'P', 'N 3% +P2O5 21% + CaO 6,3%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Deltamicro combi 1', 'AUTRE', 'kg', 'OE', 'Bore 1,4 % , Cuivre 0,7 % , Fer 4 % , Manganèse 3,2% , Zinc 3,8 % Magnésium 1 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Deltamicro combi Mg', 'AUTRE', 'kg', 'MG', 'oxyde de magnésium 6.1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('DELTAQUIN', 'AUTRE', 'l', 'Potassium + micronutriments (biostimulant de maturation)') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('DIAFFERANE', 'AUTRE', 'kg', 'Fer EDDHA') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Easimix', 'AUTRE', 'l', 'P2O5 19,5%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('EFFICIENT', 'AUTRE', 'l', 'N 28%+ FORMALDEHYD 17 P/P') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Ennerfruit', 'AUTRE', 'l', 'CaO 3%, MgO 3%, B 0,2%, Mo 0,4 %, Mn 0,1%, Zn 0,1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('ETHREL', 'AUTRE', 'l', 'Éthéphon (régulateur de croissance libérant l’éthylène)') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Excellent Fe+AA', 'AUTRE', 'kg', 'Fer + Acide aminés') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Exilis', 'AUTRE', 'l', 'Benzyladenine') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('FeriK Fer', 'AUTRE', 'kg', 'Fer Eddha') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Fixa Soufre', 'AUTRE', 'l', 'SOUFRE', 'N 9% , SO3 75%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FLORGIB', 'AUTRE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('FLOWRING', 'AUTRE', 'l', 'Phosphore + potassium + bore (stimulation floraison)') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('FOLIXDAN', 'AUTRE', 'l', 'Azote + phosphore + bore + molybdène (bio-activateur nutritif)') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('FRUIT AUXINE', 'AUTRE', 'l', 'Acide Naphtylacétique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Fruka', 'AUTRE', 'l', 'K2O, Mo, Algues') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('FULVISTAR', 'AUTRE', 'l', 'ACIDE HUMIQUE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('GA3 RIVA', 'AUTRE', 'kg', 'acide gibbérellique 10%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Goemar', 'AUTRE', 'l', 'N 4,1% B 2,07%, Mgo 4,8%, Mo 0,02%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('GOLTIX', 'AUTRE', 'l', 'Metamitrin') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Green Zn', 'AUTRE', 'kg', 'ZN', 'Zn 21%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Hockley phone', 'AUTRE', 'l', 'Ethephon 480 g/l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('HUMIK', 'AUTRE', 'l', 'ACIDE HUMIQUE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Humistar/Humagreen', 'AUTRE', 'l', 'ACIDE HUMIQUE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Kitosamine', 'AUTRE', 'kg', 'Mn 2.7%, Zn 2.3%, Carbohydrate 50%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('KMT-BDNK-23', 'AUTRE', 'l', 'Non mentionné') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Kudos', 'AUTRE', 'kg', 'Prohexadione calcium 100g/Kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Lait', 'AUTRE', 'kg', 'Lait de levée de dormance') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('LI700 STAR', 'AUTRE', 'l', '488 g/L lécithine') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Liqui K', 'AUTRE', 'l', 'Azote 3% , Oxyde de potassium 32% ,agent séquestrant 1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Liqui K express', 'AUTRE', 'kg', 'K POTASSIUM') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Mastique', 'AUTRE', 'kg', 'MASTIQUE', 'Mastique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('MAXIM', 'AUTRE', 'kg', 'Triclopyr 10%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Moliboro', 'AUTRE', 'l', 'Bore+ Molybdene') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Moussagri', 'AUTRE', 'l', 'Savon potassique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Neostren Forte', 'AUTRE', 'kg', 'Calcium 17 % Bore 1,5 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Novagib', 'AUTRE', 'l', '10g/l Gibberillines GA4/7') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Phosphite One', 'AUTRE', 'l', 'N 3%, P2O5 30%, K2O 15%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Phylgreen Alya', 'AUTRE', 'l', 'Extrait D''algues 13,5% P/P, Bore 9,2% P/P') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Plyaminol', 'AUTRE', 'l', 'AA') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Polidel', 'AUTRE', 'l', 'Azote 2,3 % , Oxyde de potassium 25,5 % , Agent séquestrant HEDTA 25,5 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Prefectos', 'AUTRE', 'l', 'Acides Aminées') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Presto', 'AUTRE', 'l', 'Ethéphon 40 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Regalis plus', 'AUTRE', 'kg', 'prohexadione-calcium 100 g/kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Rombi K', 'AUTRE', 'l', 'K', 'Azote Total 3 % , Azote Uréique 3% ,Oxyde de potassium hydrosoluble 32%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Saltrad Ca', 'AUTRE', 'l', 'ANTI SALINITE', 'CaO 7,5%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Selekter kinine', 'AUTRE', 'l', 'Cytokinine 1,6%, Matiere organique 5%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Seniphos', 'AUTRE', 'l', 'N 3% +P2O5 23.6% + CaO 4,3%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Sequestrene', 'AUTRE', 'kg', 'Fer Eddha') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Siberio', 'AUTRE', 'l', '15 % Azote Total , 6 % Azote Nitrique , 3 % Azote Ammoniacal , 6 % Azote Uréique, 4,5 % Oxyde de calcium 0, ,05 % Fer chélaté EDTA , 0,05 % Zinc Chélaté EDTA') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Specialcare amino acide', 'AUTRE', 'kg', 'AA', 'Amino acide 43% , Organic matier 20% Nitrogène 17 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Stilo racinaire', 'AUTRE', 'l', 'AA 10.5% N 2.7% Fer 4.5% Mn 1%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('SULIT', 'AUTRE', 'l', '0.93% Bore, 5.82% Molybdene') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Talc', 'AUTRE', 'kg', 'TALC', 'Talc') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Terracan', 'AUTRE', 'l', 'AH', 'Extrait Humique total + Oxyde de Potassium') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Tonofol sp', 'AUTRE', 'l', 'Mn+Zn') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('TOPPER/TERBEL', 'AUTRE', 'kg', 'Triclopyr 10%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Tradebor', 'AUTRE', 'l', 'Bore 11%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Tradecitrus', 'AUTRE', 'kg', 'Mn 6% , Zn 8%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Tradecorp Cu', 'AUTRE', 'kg', 'CU', 'Cuivre EDTA 14% p/p') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Tradecorp Mn', 'AUTRE', 'kg', 'MN', 'Mn 13%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Tradecorp Zn', 'AUTRE', 'kg', '14% ZINC EDTA') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Trainer', 'AUTRE', 'l', 'Mo, N organique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('UltraFerro', 'AUTRE', 'kg', 'Fer Eddha') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Vitanica', 'AUTRE', 'l', 'Algues') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Wuxal cu', 'AUTRE', 'l', 'CU', 'cu') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Wuxal Fer', 'AUTRE', 'l', 'Fer EDTA') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Wuxal Macromix', 'AUTRE', 'l', '24 % Azote Total , 24 % Phosphate , 18 % Potassium +OE') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('ZINBORE', 'AUTRE', 'kg', 'Bore Zinc') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Acide citrique', 'ENGRAIS', 'kg', 'AC', 'Acide citrique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('ACIDE NITRIQUE', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('ACIDE PHOSPHORIQUE', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Agriphos', 'ENGRAIS', 'l', 'AP', 'Acide Phosphorique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Agrisulf', 'ENGRAIS', 'l', 'AS', 'Acide sulfurique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Agrizote', 'ENGRAIS', 'l', 'AN', 'Acide Nitrique') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('DAP P44 MAGNUM', 'ENGRAIS', 'kg', 'N18-P44') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory) values ('FERTIGEL', 'ENGRAIS', 'l', 'GEL') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Hydro speed', 'ENGRAIS', 'kg', 'Sulfate D''ammoniaque') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('KSC1', 'ENGRAIS', 'kg', 'P', '14 % N, 40% P2o5, 5 % K2o, 13 % So3, 0,1 % B ,0,05 % Cu, 0,1 % Fe, 0,01 % Mo ,0,1 % Zn') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('MAP 12-61-00', 'ENGRAIS', 'kg', 'Np 12-61') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Matière organique', 'ENGRAIS', 'l', 'MO', 'Matiere organique liquide') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Nitrate calcium', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Nitrate de Calcium', 'ENGRAIS', 'kg', 'CA', 'N 15% - Cao 26,5%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Nitrate de Magnésium', 'ENGRAIS', 'kg', 'MG', 'N 10,5%, Mgo 16%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Nitrate de Potassium', 'ENGRAIS', 'kg', 'K', 'N13- P 0 - K 46') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('NITRATE MAGNESIUM', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Nitrate magnésium', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Nitrate potassium', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('NPK SOP', 'ENGRAIS', 'kg', 'Npk 12.12.17+2+Te') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('POTASSIUM ACID', 'ENGRAIS', 'kg', 'ACIDE + N13- P 0 - K 46') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Potassium acide 13,9.0.45', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Rombiquel Magnesio', 'ENGRAIS', 'l', 'Oxyde De Magnésium 8,5 %') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Sulfate d’ammonium', 'ENGRAIS', 'kg', 'N21') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Sulfate de Mg', 'ENGRAIS', 'kg', 'Mgo 16%+So3 32%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('Sulfate de Potassium', 'ENGRAIS', 'kg', 'K2o 51%+So3 45%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Sulphate ammonium', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('UAN 32%', 'ENGRAIS', 'l', 'N 32%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, composition) values ('UREA PHOSPHATE', 'ENGRAIS', 'kg', '17.44.00') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Urea phosphaté(N17,5 P44)', 'ENGRAIS', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, subcategory, composition) values ('Urée 46', 'ENGRAIS', 'kg', 'N', 'N 46%') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Aktuan', 'FONGICIDE', 'kg', 'Dimethomorphe 150 g/kg, Dithianon 350 g/kg', (select id from lf_active_ingredients where name = 'Dimethomorphe 150 g/kg, Dithianon 350 g/kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Aliette flash', 'FONGICIDE', 'kg', 'Fosétyl-Aluminium 80 %', (select id from lf_active_ingredients where name = 'Fosétyl-Aluminium 80 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Amistar top', 'FONGICIDE', 'l', 'Difenoconazole 125 g/l, Azoxystrobine 200 g/l', (select id from lf_active_ingredients where name = 'Difenoconazole 125 g/l, Azoxystrobine 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Antracol', 'FONGICIDE', 'kg', 'Propineb 70%', (select id from lf_active_ingredients where name = 'Propineb 70%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Bayfidan', 'FONGICIDE', 'l', 'Triadimenol 250 g/L', (select id from lf_active_ingredients where name = 'Triadimenol 250 g/L')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('BELANTY', 'FONGICIDE', 'l', '75 g/L méfentrifluconazole', (select id from lf_active_ingredients where name = '75 g/L méfentrifluconazole')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Bellis', 'FONGICIDE', 'kg', 'Boscalid 252 g/kg, Pyraclostrobine 128 g/kg', (select id from lf_active_ingredients where name = 'Boscalid 252 g/kg, Pyraclostrobine 128 g/kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Bouillie bordelaise', 'FONGICIDE', 'kg', 'Sulfate de cuivre 80%', (select id from lf_active_ingredients where name = 'Sulfate de cuivre 80%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Cabrio', 'FONGICIDE', 'l', 'Dimethomorphe 72 g/l, Pyraclotrobine 40 g/l', (select id from lf_active_ingredients where name = 'Dimethomorphe 72 g/l, Pyraclotrobine 40 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Chorus', 'FONGICIDE', 'kg', 'Cyprodinil 50%', (select id from lf_active_ingredients where name = 'Cyprodinil 50%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Click', 'FONGICIDE', 'kg', 'Dithianon 70%', (select id from lf_active_ingredients where name = 'Dithianon 70%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Collis', 'FONGICIDE', 'l', 'Boscalid 200 g/l, Krésoxim-Methyl 100 g/l', (select id from lf_active_ingredients where name = 'Boscalid 200 g/l, Krésoxim-Methyl 100 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Corail', 'FONGICIDE', 'l', 'Tebuconazole 250 g/l', (select id from lf_active_ingredients where name = 'Tebuconazole 250 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Criptan', 'FONGICIDE', 'kg', 'Captan 50% WP', (select id from lf_active_ingredients where name = 'Captan 50% WP')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Delan', 'FONGICIDE', 'l', 'Dithianon 500 g/l', (select id from lf_active_ingredients where name = 'Dithianon 500 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Domarek', 'FONGICIDE', 'l', 'Tetraconazole 40 g/l', (select id from lf_active_ingredients where name = 'Tetraconazole 40 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Flint', 'FONGICIDE', 'kg', 'Thiafloxystrobine 50%', (select id from lf_active_ingredients where name = 'Thiafloxystrobine 50%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FOLIETTE/GOLDFOS', 'FONGICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Fongichell', 'FONGICIDE', 'l', 'Cuivre 4,5%', (select id from lf_active_ingredients where name = 'Cuivre 4,5%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Helio cuivre', 'FONGICIDE', 'l', 'Hydroxyde de cuivre 400 g/l', (select id from lf_active_ingredients where name = 'Hydroxyde de cuivre 400 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Inacop', 'FONGICIDE', 'l', 'Oxychlorure de Cuivre 678,6 g/l', (select id from lf_active_ingredients where name = 'Oxychlorure de Cuivre 678,6 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Luna experience', 'FONGICIDE', 'l', 'Tebuconazole 200 g/l, Fluopyram 200 g/l', (select id from lf_active_ingredients where name = 'Tebuconazole 200 g/l, Fluopyram 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Malvin', 'FONGICIDE', 'kg', 'Captan 80% WG', (select id from lf_active_ingredients where name = 'Captan 80% WG')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Merit', 'FONGICIDE', 'l', 'Difenoconazole, Azoxystrobine', (select id from lf_active_ingredients where name = 'Difenoconazole, Azoxystrobine')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Methyl Thiophanate', 'FONGICIDE', 'kg', 'Thiophanate methyl', (select id from lf_active_ingredients where name = 'Thiophanate methyl')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Microtheol 80', 'FONGICIDE', 'kg', 'Soufre Miconisé Atomisé', (select id from lf_active_ingredients where name = 'Soufre Miconisé Atomisé')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Mikal flash', 'FONGICIDE', 'kg', 'Fosetyl Aluminium 500 g/kg, Folpel 250 g/kg', (select id from lf_active_ingredients where name = 'Fosetyl Aluminium 500 g/kg, Folpel 250 g/kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Nando', 'FONGICIDE', 'l', 'Fluazinam 500g/l', (select id from lf_active_ingredients where name = 'Fluazinam 500g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Profiler', 'FONGICIDE', 'kg', 'Fosetyl Aluminium 666,7g/Kg, Fluopicolide 444g/Kg', (select id from lf_active_ingredients where name = 'Fosetyl Aluminium 666,7g/Kg, Fluopicolide 444g/Kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Prosper', 'FONGICIDE', 'l', 'Spiroxamine 300 g/l', (select id from lf_active_ingredients where name = 'Spiroxamine 300 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Ridomil', 'FONGICIDE', 'kg', 'Fo Métalaxyl-M 5%, Folpel 40 %', (select id from lf_active_ingredients where name = 'Fo Métalaxyl-M 5%, Folpel 40 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Score', 'FONGICIDE', 'l', 'Difénoconazole 250 g/l', (select id from lf_active_ingredients where name = 'Difénoconazole 250 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Stroby', 'FONGICIDE', 'kg', 'Keroxim Methyl 50%', (select id from lf_active_ingredients where name = 'Keroxim Methyl 50%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Switch', 'FONGICIDE', 'kg', 'Cyprodinil 37,5 %, Fludioxonil 25 %', (select id from lf_active_ingredients where name = 'Cyprodinil 37,5 %, Fludioxonil 25 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Syllit', 'FONGICIDE', 'l', 'Dodine 400 g/l', (select id from lf_active_ingredients where name = 'Dodine 400 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Systhane', 'FONGICIDE', 'l', 'Myclobutanil 240 g/L', (select id from lf_active_ingredients where name = 'Myclobutanil 240 g/L')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Talendo', 'FONGICIDE', 'l', 'Proquinazid 200 g/l', (select id from lf_active_ingredients where name = 'Proquinazid 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Teldor', 'FONGICIDE', 'kg', 'Fenhexamid 500 g/kg', (select id from lf_active_ingredients where name = 'Fenhexamid 500 g/kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Thiramchim', 'FONGICIDE', 'kg', 'Thiram 80 %', (select id from lf_active_ingredients where name = 'Thiram 80 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Tizca', 'FONGICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Topaze', 'FONGICIDE', 'l', 'Penconazole 100 g/l', (select id from lf_active_ingredients where name = 'Penconazole 100 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Valette', 'FONGICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Valtera', 'FONGICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('VAPCOTOP', 'FONGICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Vitene Triplo R', 'FONGICIDE', 'kg', 'Cymoxanil 2,85% w/w + Fosetyl Aluminum 30% w/w + Cuivre 16% w/w', (select id from lf_active_ingredients where name = 'Cymoxanil 2,85% w/w + Fosetyl Aluminum 30% w/w + Cuivre 16% w/w')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Vivando', 'FONGICIDE', 'l', 'Metrafenone 500 g/l', (select id from lf_active_ingredients where name = 'Metrafenone 500 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Volar cu', 'FONGICIDE', 'kg', 'Dimethomorphe 60 g/kg, cuivre 400 g/kg', (select id from lf_active_ingredients where name = 'Dimethomorphe 60 g/kg, cuivre 400 g/kg')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Alion', 'HERBICIDE', 'l', 'Indaziflam 500 g/L', (select id from lf_active_ingredients where name = 'Indaziflam 500 g/L')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Basta', 'HERBICIDE', 'l', 'Glufosinate Ammonium 15 g/l', (select id from lf_active_ingredients where name = 'Glufosinate Ammonium 15 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('FLUENT', 'HERBICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Focus', 'HERBICIDE', 'l', 'Cycloxydine', (select id from lf_active_ingredients where name = 'Cycloxydine')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('FUSILAD', 'HERBICIDE', 'l', 'FLUAZIFOP-P-BUTYL', (select id from lf_active_ingredients where name = 'FLUAZIFOP-P-BUTYL')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Ground UP', 'HERBICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('HADDAF', 'HERBICIDE', 'l', 'Oxyfluorfen 240 g/l', (select id from lf_active_ingredients where name = 'Oxyfluorfen 240 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Rivasate', 'HERBICIDE', 'l', 'Glyphosate', (select id from lf_active_ingredients where name = 'Glyphosate')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('TOPPER', 'HERBICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Absolute', 'INSECTICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Actara', 'INSECTICIDE', 'kg', 'Thiamethoxam WG 25 %', (select id from lf_active_ingredients where name = 'Thiamethoxam WG 25 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Agroil Blue', 'INSECTICIDE', 'l', 'Huile de paraffine 830 g/L', (select id from lf_active_ingredients where name = 'Huile de paraffine 830 g/L')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('ALEMBRA', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('APOLLO', 'INSECTICIDE', 'l', 'CLOFENTEZINE+ BIFENTHRINE', (select id from lf_active_ingredients where name = 'CLOFENTEZINE+ BIFENTHRINE')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Bactimec', 'INSECTICIDE', 'l', 'Abamectine 18 g/l', (select id from lf_active_ingredients where name = 'Abamectine 18 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('BATON', 'INSECTICIDE', 'l', 'Bifenthrine', (select id from lf_active_ingredients where name = 'Bifenthrine')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Beidazit', 'INSECTICIDE', 'kg', 'Huile Minérale 76 %', (select id from lf_active_ingredients where name = 'Huile Minérale 76 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Calypso', 'INSECTICIDE', 'l', 'Thiaclopride 280 g/l', (select id from lf_active_ingredients where name = 'Thiaclopride 280 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Cetan', 'INSECTICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('COLT', 'INSECTICIDE', 'l', 'PYRIFLUQUINAZON 20 %', (select id from lf_active_ingredients where name = 'PYRIFLUQUINAZON 20 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Cominal', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Commando', 'INSECTICIDE', 'l', 'Imidaclopride', (select id from lf_active_ingredients where name = 'Imidaclopride')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Confidor', 'INSECTICIDE', 'l', 'Imidaclopride OD 200 g/l', (select id from lf_active_ingredients where name = 'Imidaclopride OD 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Decis expert', 'INSECTICIDE', 'l', 'Deltamethrine 25g/l', (select id from lf_active_ingredients where name = 'Deltamethrine 25g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('DEKAPLUS', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('DIMETHOATE', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('DRAGON', 'INSECTICIDE', 'l', 'Spinosad', (select id from lf_active_ingredients where name = 'Spinosad')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Eltoro', 'INSECTICIDE', 'l', 'Thiamethoxam SC 25 %', (select id from lf_active_ingredients where name = 'Thiamethoxam SC 25 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Envidor', 'INSECTICIDE', 'l', 'Spirodiclofen 240 g/l', (select id from lf_active_ingredients where name = 'Spirodiclofen 240 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Exirel', 'INSECTICIDE', 'l', 'Cyantraniliprole', (select id from lf_active_ingredients where name = 'Cyantraniliprole')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Fastac', 'INSECTICIDE', 'l', 'Alpha-Cyperméthrine 100 g/l', (select id from lf_active_ingredients where name = 'Alpha-Cyperméthrine 100 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Floramite', 'INSECTICIDE', 'l', 'Bifénazate 240 g/l', (select id from lf_active_ingredients where name = 'Bifénazate 240 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Foslete', 'INSECTICIDE', 'kg', 'Phosmet 50%', (select id from lf_active_ingredients where name = 'Phosmet 50%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Fourmicide', 'INSECTICIDE', 'kg', 'Chlorpyriphos 2%', (select id from lf_active_ingredients where name = 'Chlorpyriphos 2%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('General', 'INSECTICIDE', 'l', 'Pyriproxifène 100 g/l', (select id from lf_active_ingredients where name = 'Pyriproxifène 100 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Hexithiazox', 'INSECTICIDE', 'kg', 'Hexythiazox', (select id from lf_active_ingredients where name = 'Hexythiazox')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Insegar', 'INSECTICIDE', 'kg', 'Fenoxycarbe 25 %', (select id from lf_active_ingredients where name = 'Fenoxycarbe 25 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('KANEMITE', 'INSECTICIDE', 'l', 'Acequinocyl', (select id from lf_active_ingredients where name = 'Acequinocyl')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('KAOROFOURMI', 'INSECTICIDE', 'kg') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Karaté', 'INSECTICIDE', 'l', 'Lambda cyhalothrine', (select id from lf_active_ingredients where name = 'Lambda cyhalothrine')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Masai', 'INSECTICIDE', 'kg', 'Tebufenpyrad', (select id from lf_active_ingredients where name = 'Tebufenpyrad')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Match Gold', 'INSECTICIDE', 'l', 'Lufenuron 50 g/l', (select id from lf_active_ingredients where name = 'Lufenuron 50 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Metheoate', 'INSECTICIDE', 'l', 'Dimétoate', (select id from lf_active_ingredients where name = 'Dimétoate')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Mitigate', 'INSECTICIDE', 'l', 'Fenpyroximate 5%', (select id from lf_active_ingredients where name = 'Fenpyroximate 5%')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Movento', 'INSECTICIDE', 'l', 'Spirotetramat', (select id from lf_active_ingredients where name = 'Spirotetramat')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('NEGMITE', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('NOMOLT', 'INSECTICIDE', 'l', 'Teflubenzuron 150g/l', (select id from lf_active_ingredients where name = 'Teflubenzuron 150g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('NUMECTINE', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Oberon', 'INSECTICIDE', 'l', 'Spiromesifen 240 g/l', (select id from lf_active_ingredients where name = 'Spiromesifen 240 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Picador', 'INSECTICIDE', 'l', 'Acétamepride SL 200 g/l', (select id from lf_active_ingredients where name = 'Acétamepride SL 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('ProAct', 'INSECTICIDE', 'l', 'Emamectin Benzoate 50 g/l', (select id from lf_active_ingredients where name = 'Emamectin Benzoate 50 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Pyrical', 'INSECTICIDE', 'l', 'Chlorpyriphos 480g/l', (select id from lf_active_ingredients where name = 'Chlorpyriphos 480g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Radiant', 'INSECTICIDE', 'l', 'Spinetoram 120 g/l', (select id from lf_active_ingredients where name = 'Spinetoram 120 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Riben', 'INSECTICIDE', 'kg', 'Pyridabene 20 %', (select id from lf_active_ingredients where name = 'Pyridabene 20 %')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Rufast', 'INSECTICIDE', 'l', 'Acrinathrine 75 g/l', (select id from lf_active_ingredients where name = 'Acrinathrine 75 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Sam Huile', 'INSECTICIDE', 'l', 'Huile Blanche', (select id from lf_active_ingredients where name = 'Huile Blanche')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Shirudo', 'INSECTICIDE', 'l', 'Tolfenpyrad', (select id from lf_active_ingredients where name = 'Tolfenpyrad')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Sivanto', 'INSECTICIDE', 'l', 'Flupyradifurone 200 g/l', (select id from lf_active_ingredients where name = 'Flupyradifurone 200 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Smash', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('SPANOCEST', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('SPINOX', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Tebumight', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit) values ('Tracer', 'INSECTICIDE', 'l') on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Trebon', 'INSECTICIDE', 'l', 'Etofenprox 287,5 g/l', (select id from lf_active_ingredients where name = 'Etofenprox 287,5 g/l')) on conflict (name, category) do nothing;
insert into lf_products (name, category, unit, active_ingredient_text, active_ingredient_id) values ('Voliam flexi', 'INSECTICIDE', 'l', 'Thiamethoxam 200 g/l , chlorantraniliprole 100 g/l', (select id from lf_active_ingredients where name = 'Thiamethoxam 200 g/l , chlorantraniliprole 100 g/l')) on conflict (name, category) do nothing;